config/routes.rb
Rails.application.routes.draw do
  root to: "questions#index"
  resources :questions do
    resources :options
  end
end

app/models/option.rb
class Option < ActiveRecord::Base
  belongs_to :question
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  validates :description, presence: true
end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :options
  accepts_nested_attributes_for :options
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/options_controller.rb
class OptionsController < ApplicationController
  def update
    @question = Question.find(params[:question_id])
    @option = @question.options.find(params[:id])
    if @option.update(score: @option.score + 1)
      respond_to do |format|
        format.html { redirect_to questions_path }
        format.js
      end
    end
  end

# because we are only updating score we can just use an update on the score. instead of embedding it into the link

  private

  def option_params
    params.require(:option).permit(:description, :score, :image)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.all
  end

  def new
    @question = Question.new
    1.times { @question.options.build }
    # builds nested form ..use 1.times as a way of building the form for field
  end

  def create
    @question = Question.new(question_params)
    if @question.save()
      respond_to do |format|
        format.html {redirect_to questions_path}
        format.js
      end
    else
      render :new
    end
  end

  def show
    @question = Question.find(params[:id])
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def question_params
    params.require(:question).permit(:name, options_attributes: [:description, :image])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rather</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/options/update.js.erb
$(".option span#<%= @option.id %>").text("<%= @option.score %>");

app/views/questions/_form.html.erb
<!-- <%= form_for @question do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <label for="option_a">Option A</label>
  <input type="text" name="option_a" value="">
  <label for="option_b">Option B</label>
  <input type="text" name="option_b" value="">
  <%= f.submit %>
<% end %> -->

<%= form_for @question, id: "new_question", remote: true, authenticity_token: true do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.fields_for :options do |option_fields| %>
    <%= option_fields.label :description, "Option A" %>
    <%= option_fields.text_field :description %>
    <%= option_fields.file_field :image %>
  <% end %>
<br />
  <%= f.fields_for :options do |option_fields| %>
    <%= option_fields.label :description, "Option B" %>
    <%= option_fields.text_field :description %>
    <%= option_fields.file_field :image %>
  <% end %>
  <%= f.submit %>
<% end %>

<!-- Nested form in rails terms. -->
<!-- 
authenticitiy_token :true allows for paper-clip to work in ajax -->

app/views/questions/_question.html.erb
<li>
  <%= link_to @question.name, question_path(@question) %>
  <ul>
    <% @question.options.each do |option| %>
      <li> <%= option.description %> </li>
    <% end %>
  </ul>
</li>

<!-- 
@question is refering to @question in the controller def create -->

app/views/questions/create.js.erb
$('#new_question').remove();
$('#new_question_link').show();
$('#questions').append("<%= j render(@question) %>")

// 
// @question refers to @question in the controller but looks for the partial _question.html.erb

app/views/questions/index.html.erb
<h1>All questions</h1>
<ul id="questions">

  <% @questions.each do |question| %>
    <li><%= link_to question.name, question_path(question) %></li>
      <ul>
        <% question.options.order(created_at: :desc).each do |option| %>
          <li class="option"><%= link_to "vote", question_option_path(question, option), remote: true, method: :patch %> <%= option.description %> - <span id="<%= option.id %>"><%= option.score %></span></li>
          <li> <%= image_tag option.image%></li>
        <% end %>
      </ul>
  <% end %>
</ul>

<%= link_to "New Question", new_question_path, id: "new_question_link", class:"btn btn-default", remote: true%>

app/views/questions/new.html.erb
<%= render "form" %>

app/views/questions/new.js.erb
$('#new_question_link').hide().after('<%= j render("form") %>')

app/views/questions/show.html.erb
<h1> <%= @question.name %> </h1>
<ul>
  <% @question.options.each do |option| %>
    <li> <%= option.description %> </li>
  <% end %>
</ul>